bank: !!python/unicode 'Musterbankw'
bic: !!python/unicode 'SOLADES1MEI'
firstname: !!python/unicode 'Paulo'
iban: !!python/unicode 'DE04850550004000090181'
id: !!python/unicode '012345'
name: !!python/unicode 'Kuntke'
street: "Musterstra\xDFe 42"
town: !!python/unicode 'Musterstadt'
ustnr: ''
zip: !!python/unicode '012345'
