bank: !!python/unicode 'Musterbankw'
bankid: !!python/unicode '123 123 0000'
deposit: !!python/unicode '9900990000'
firstname: !!python/unicode 'Paulo'
id: !!python/unicode '012345'
name: !!python/unicode 'Kuntke'
street: "Musterstra\xDFe 42"
town: !!python/unicode 'Musterstadt'
ustnr: ''
zip: !!python/unicode '012345'
