bank: !!python/unicode 'BANK'
bic: !!python/unicode ''
firstname: !!python/unicode 'Vorname'
iban: !!python/unicode 'DE38850550004000232741'
id: !!python/unicode 'Beraternummer'
name: !!python/unicode 'Name'
street: !!python/unicode 'Strasse'
town: !!python/unicode 'Stadt'
ust:
- from: 200901
  value: 19
- from: 201405
  value: 21
ustnr: ''
zip: !!python/unicode 'PLZ'
